version: '3'
services:
  nginx:
    image: macbre/nginx-http3:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - 443:443/udp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/etc:/etc/letsencrypt:ro
    depends_on:
      - ctf_app

  ctf_app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: ctf_app
      restart: always
      ports:
        - "3000:3000"
      command: npm run start
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - NODE_ENV=production
